#! /usr/bin/env bash

lb config noauto \
    -b iso-hybrid \
    --debian-installer live \
    --system live \
    --apt-http-proxy http://192.168.1.203:3142 \
    --backports true \
    --image-name awesome \
    -d stretch \
    --parent-distribution stretch \
    --debootstrap-options "--merged-usr --variant=minbase --include=busybox-syslogd,gnupg2,gpgv-static,apt-transport-https,gnutls-bin" \
    --initsystem sysvinit \
    --parent-mirror-bootstrap http://ftp.us.debian.org/debian/ \
    "$@"
